# Generated by Django 5.0.2 on 2024-02-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_icon',
            field=models.ImageField(blank=True, default='', upload_to='profiles/icons/'),
        ),
    ]
